import express from "express";
import { authorizeRoles, isAuthenticated } from "../middlewares/auth.middleware.js";
import { createNewAsset, deleteAsset, getAllAssets, getAssetBySno, getAssetStats, getRepairLogById, getRepairLogs, getUserAssets, updateAssetDetails } from "../controllers/asset.controller.js";
const router = express.Router();
router.get("/assets", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getAllAssets);
router.post("/assets", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), createNewAsset);
router.get("/assets/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getAssetBySno);
router.put("/assets/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), updateAssetDetails);
router.delete("/assets/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), deleteAsset);
router.get("/assets/stats", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getAssetStats);
router.get("/repairs", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getRepairLogs);
router.get("/repairs/:id", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getRepairLogById );
router.get("/me/assets", isAuthenticated, getUserAssets);
router.get("/dashboard/assets/stats", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getAssetStats);
export default router;
