import express from "express";
import { authorizeRoles, isAuthenticated } from "../middlewares/auth.middleware.js";
import { getAllAssignments, getMyAssignments, getMyReturnedAssets, getUserAssignments, recordAssetAssignment, recordAssetRepaired, recordAssetRetired, recordAssetReturn, recordRepairAsset } from "../controllers/assetAssignment.controller.js";
const router = express.Router();
router.post("/recordAssetAssignment/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), recordAssetAssignment);
router.post("/recordAssetReturn/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), recordAssetReturn);
router.post("/recordAssetRepair/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), recordRepairAsset);
router.post("/recordAssetRepaired/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), recordAssetRepaired);
router.post("/recordAssetRetired/:sno", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), recordAssetRetired);
router.get("/getAllAssignments", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getAllAssignments);
router.get("/getAllAssignments/:userId", isAuthenticated, authorizeRoles("Admin", "Asset Manager"), getUserAssignments);
router.get("/my-assignments", isAuthenticated, getMyAssignments);
router.get("/my-returned-assets", isAuthenticated, getMyReturnedAssets);
export default router;
